---
server:
  port: 1415
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/hufsSchedule
  jpa:
    hibernate:
      ddl-auto: create

#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    show-sql: true
  cache: redis
  redis:
    host: hufsschedulesystemredis.kbfcki.ng.0001.apn2.cache.amazonaws.com
    port: 6379



#    spring:
#      datasource:
#        url: jdbc:h2:tcp://localhost/~/noti
#        username: sa
#        password:
#        driver-class-name: org.h2.Driver
#      #    driver-class-name: com.mysql.cj.jdbc.Driver
#      #    url: jdbc:mysql://localhost:3306/demo
#      #    username: root
#      #    password: Skdmlwn1323!
#      jpa:
#        hibernate:
#          ddl-auto: create
#        properties:
#          hibernate:
#            format_sql: true
#
#    logging:
#      level:
#        org.hibernate.SQL: debug
#        org.hibernate.type: trace