# Generated by Django 2.2.6 on 2020-04-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=20)),
                ('year', models.IntegerField(null=True)),
                ('course_num', models.CharField(max_length=15)),
                ('subject_name', models.CharField(max_length=200)),
                ('syllabus', models.CharField(max_length=500)),
                ('required', models.BooleanField()),
                ('professor', models.CharField(max_length=100)),
                ('credit', models.IntegerField()),
                ('class_time', models.CharField(max_length=100)),
                ('restricted_num', models.CharField(max_length=20)),
                ('note', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Furits',
        ),
    ]
