# Generated by Django 2.2.6 on 2020-04-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0005_auto_20200402_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_course', models.IntegerField()),
                ('instruction_number', models.IntegerField()),
            ],
            options={
                'db_table': 'Courses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_table', models.IntegerField()),
                ('instruction_number', models.IntegerField()),
            ],
            options={
                'db_table': 'TimeTable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_number', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=45)),
                ('major', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'User',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('instruction_id', models.AutoField(primary_key=True, serialize=False)),
                ('instruction_number', models.CharField(max_length=15)),
                ('dept', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=20)),
                ('year', models.IntegerField(null=True)),
                ('subject_name', models.CharField(max_length=200)),
                ('syllabus', models.CharField(max_length=500)),
                ('required', models.BooleanField()),
                ('professor', models.CharField(max_length=100)),
                ('credit', models.IntegerField()),
                ('time', models.IntegerField()),
                ('class_time', models.CharField(max_length=100)),
                ('number_of_people', models.IntegerField()),
                ('note', models.CharField(max_length=1000)),
            ],
            options={
                'unique_together': {('subject_name', 'professor', 'class_time')},
            },
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
