# Generated by Django 3.0.5 on 2020-04-11 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('student_number', models.IntegerField(unique=True)),
                ('major', models.CharField(max_length=100)),
                ('second_major', models.CharField(blank=True, max_length=100, null=True)),
                ('minor', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.BooleanField(blank=True, null=True)),
                ('foreign', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Insturction',
            fields=[
                ('instruction_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=40)),
                ('dept', models.CharField(max_length=100)),
                ('required', models.IntegerField()),
                ('professor', models.CharField(max_length=100)),
                ('credit', models.IntegerField()),
                ('time', models.IntegerField()),
                ('class_time', models.CharField(max_length=10)),
                ('number_of_people', models.CharField(max_length=25)),
                ('note', models.CharField(max_length=400)),
                ('subject', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('rq_year', models.CharField(max_length=10)),
                ('rq_semester', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Instruction',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('instruction_number', models.ForeignKey(db_column='instruction_number', on_delete=django.db.models.deletion.DO_NOTHING, to='crawl.Insturction')),
                ('user_table', models.ForeignKey(db_column='user_table', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Timetable',
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('credit_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_major', models.IntegerField()),
                ('second_major', models.IntegerField()),
                ('sub_major', models.IntegerField()),
                ('minor', models.IntegerField()),
                ('outdoor', models.IntegerField()),
                ('liberal_arts', models.IntegerField()),
                ('teaching', models.IntegerField()),
                ('total_credit', models.IntegerField()),
                ('optional', models.IntegerField()),
                ('user_credit', models.OneToOneField(db_column='user_credit', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Credit',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('instruction_number', models.ForeignKey(db_column='instruction_number', on_delete=django.db.models.deletion.DO_NOTHING, to='crawl.Insturction')),
                ('user_course', models.ForeignKey(db_column='user_course', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Course',
            },
        ),
    ]
