# Generated by Django 3.0.5 on 2020-04-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_auto_20200411_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
