# Generated by Django 3.0.5 on 2020-04-11 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0003_auto_20200411_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='average_score',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
