# Generated by Django 3.0.5 on 2020-04-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0004_credit_average_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='instruction_number',
            new_name='course_inst_num',
        ),
        migrations.RenameField(
            model_name='timetable',
            old_name='instruction_number',
            new_name='timetable_inst_num',
        ),
    ]
