# Generated by Django 3.0.5 on 2020-04-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0005_auto_20200411_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teaching',
            field=models.BooleanField(default=False),
        ),
    ]
